### ISSUE TITLE
0.8.4 throws NoSuchMethodError from PublishOptions.kt:51 where 0.7.4 works

### ISSUE THREAD

**Issue by AtomicStryker** [modmuss50/mod-publish-plugin#74]
Different issue than the other one, a build.gradle that works with mod-publish-plugin 0.7.4 does no longer work with 0.8.4

gradle output:
Could not create domain object 'curseforge' (Curseforge)

Versions used:
Gradle 8.7 [MinecraftForge 1.21.6]
Eclipse Adoptium\jdk-21.0.7.6-hotspot

Error appears to be:
Caused by: java.lang.NoSuchMethodError: 'org.gradle.api.file.ConfigurableFileCollection org.gradle.api.file.ConfigurableFileCollection.convention(java.lang.Iterable)'
        at me.modmuss50.mpp.PublishOptions.from(PublishOptions.kt:51)

Stacktrace:

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'FinderCompass'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:137)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:79)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:140)
...
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: java.lang.IllegalStateException: Could not create domain object 'curseforge' (Curseforge)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.domainObjectCreationException(DefaultNamedDomainObjectCollection.java:1045)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:1017)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.calculateOwnValue(DefaultNamedDomainObjectCollection.java:991)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
        at org.gradle.api.internal.provider.Collectors$ElementFromProvider.collectEntries(Collectors.java:120)
        at org.gradle.api.internal.provider.Collectors$TypedCollector.collectEntries(Collectors.java:415)
        at org.gradle.api.internal.provider.Collectors$TypedCollector.collectInto(Collectors.java:410)
        at org.gradle.api.internal.collections.SortedSetElementSource.realize(SortedSetElementSource.java:141)
        at org.gradle.api.internal.collections.SortedSetElementSource.addPending(SortedSetElementSource.java:169)
        at org.gradle.api.internal.DefaultDomainObjectCollection.addLater(DefaultDomainObjectCollection.java:274)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.addLater(DefaultNamedDomainObjectCollection.java:158)
        at org.gradle.api.internal.AbstractPolymorphicDomainObjectContainer.createDomainObjectProvider(AbstractPolymorphicDomainObjectContainer.java:91)
        at org.gradle.api.internal.AbstractPolymorphicDomainObjectContainer.register(AbstractPolymorphicDomainObjectContainer.java:83)
        at me.modmuss50.mpp.ModPublishExtension.curseforge(ModPublishExtension.kt:233)
        at me.modmuss50.mpp.ModPublishExtension.curseforge(ModPublishExtension.kt:69)
        at me.modmuss50.mpp.ModPublishExtension.curseforge(ModPublishExtension.kt:63)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:541)
...
        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:38)
        at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:138)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
        at org.gradle.api.internal.project.DefaultDynamicLookupRoutine.invokeMethod(DefaultDynamicLookupRoutine.java:58)
        at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:87)
        at build_etkw2vgxd5q995vn0g5bxr6bz.run(C:\Users\AtomicStryker\Documents\mcmodding\1.21.6\FinderCompass\build.gradle:127)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
        ... 164 more
Caused by: java.lang.NoSuchMethodError: 'org.gradle.api.file.ConfigurableFileCollection org.gradle.api.file.ConfigurableFileCollection.convention(java.lang.Iterable)'
        at me.modmuss50.mpp.PublishOptions.from(PublishOptions.kt:51)
        at me.modmuss50.mpp.ModPublishExtension$3.invoke(ModPublishExtension.kt:41)
        at me.modmuss50.mpp.ModPublishExtension$3.invoke(ModPublishExtension.kt:40)
        at me.modmuss50.mpp.ModPublishExtension._init_$lambda$1(ModPublishExtension.kt:40)
        at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:122)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:107)
        at org.gradle.internal.ImmutableActionSet$SetWithFewActions.execute(ImmutableActionSet.java:285)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:262)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.doAdd(DefaultNamedDomainObjectCollection.java:125)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:256)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:1011)
        ... 204 more

**Comment by modmuss50** [comment]
You need to update Gradle, this was caused by a Gradle change when we started compling with the newer version (8.10)

**Comment by AtomicStryker** [comment]
Thanks. I don't believe i can control the gradle version with minecraftforge SDK, but it is good to know.
